//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHotel.Business.Statistics {
    
    
    public partial class IncomesStatisticsForm {
        
        /// <summary>
        /// DateRangerPeriod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyHotel.Business.WebControls.DateRange.DateRangerControl DateRangerPeriod;
        
        /// <summary>
        /// IncomesViewCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyHotel.Business.WebControls.Incomes.IncomesControl IncomesViewCtrl;
    }
}
