//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHotel.Business.RoomBookingMgmt {
    
    
    public partial class RoomBookingMgmtForm {
        
        /// <summary>
        /// DateRangerPeriod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyHotel.Business.WebControls.DateRange.DateRangerControl DateRangerPeriod;
        
        /// <summary>
        /// CheckBoxEditPast control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox CheckBoxEditPast;
        
        /// <summary>
        /// BookingViewCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MyHotel.Business.WebControls.Booking.BookingsWebControl BookingViewCtrl;
    }
}
