#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHotel.LINQDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_99B829_UkrRoot")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    partial void InsertRoomBooking(RoomBooking instance);
    partial void UpdateRoomBooking(RoomBooking instance);
    partial void DeleteRoomBooking(RoomBooking instance);
    partial void InsertExpensesItem(ExpensesItem instance);
    partial void UpdateExpensesItem(ExpensesItem instance);
    partial void DeleteExpensesItem(ExpensesItem instance);
    partial void InsertExpensesDetail(ExpensesDetail instance);
    partial void UpdateExpensesDetail(ExpensesDetail instance);
    partial void DeleteExpensesDetail(ExpensesDetail instance);
    partial void InsertCleaning(Cleaning instance);
    partial void UpdateCleaning(Cleaning instance);
    partial void DeleteCleaning(Cleaning instance);
    partial void InsertUtilitiesItem(UtilitiesItem instance);
    partial void UpdateUtilitiesItem(UtilitiesItem instance);
    partial void DeleteUtilitiesItem(UtilitiesItem instance);
    partial void InsertUtilitiesItemsDetail(UtilitiesItemsDetail instance);
    partial void UpdateUtilitiesItemsDetail(UtilitiesItemsDetail instance);
    partial void DeleteUtilitiesItemsDetail(UtilitiesItemsDetail instance);
    partial void InsertCustomData(CustomData instance);
    partial void UpdateCustomData(CustomData instance);
    partial void DeleteCustomData(CustomData instance);
    #endregion
		
		public DataClassesDataContext() :
        base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MyHotelDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Room> Rooms
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<RoomBooking> RoomBookings
		{
			get
			{
				return this.GetTable<RoomBooking>();
			}
		}
		
		public System.Data.Linq.Table<ExpensesItem> ExpensesItems
		{
			get
			{
				return this.GetTable<ExpensesItem>();
			}
		}
		
		public System.Data.Linq.Table<ExpensesDetail> ExpensesDetails
		{
			get
			{
				return this.GetTable<ExpensesDetail>();
			}
		}
		
		public System.Data.Linq.Table<Cleaning> Cleanings
		{
			get
			{
				return this.GetTable<Cleaning>();
			}
		}
		
		public System.Data.Linq.Table<UtilitiesItem> UtilitiesItems
		{
			get
			{
				return this.GetTable<UtilitiesItem>();
			}
		}
		
		public System.Data.Linq.Table<UtilitiesItemsDetail> UtilitiesItemsDetails
		{
			get
			{
				return this.GetTable<UtilitiesItemsDetail>();
			}
		}
		
		public System.Data.Linq.Table<CustomData> CustomDatas
		{
			get
			{
				return this.GetTable<CustomData>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoomID;
		
		private string _Name;
		
		private int _Capacity;
		
		private EntitySet<RoomBooking> _RoomBookings;
		
		private EntitySet<Cleaning> _Cleanings;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoomIDChanging(int value);
    partial void OnRoomIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnCapacityChanging(int value);
    partial void OnCapacityChanged();
    #endregion
		
		public Room()
		{
			this._RoomBookings = new EntitySet<RoomBooking>(new Action<RoomBooking>(this.attach_RoomBookings), new Action<RoomBooking>(this.detach_RoomBookings));
			this._Cleanings = new EntitySet<Cleaning>(new Action<Cleaning>(this.attach_Cleanings), new Action<Cleaning>(this.detach_Cleanings));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoomID
		{
			get
			{
				return this._RoomID;
			}
			set
			{
				if ((this._RoomID != value))
				{
					this.OnRoomIDChanging(value);
					this.SendPropertyChanging();
					this._RoomID = value;
					this.SendPropertyChanged("RoomID");
					this.OnRoomIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Capacity", DbType="Int NOT NULL")]
		public int Capacity
		{
			get
			{
				return this._Capacity;
			}
			set
			{
				if ((this._Capacity != value))
				{
					this.OnCapacityChanging(value);
					this.SendPropertyChanging();
					this._Capacity = value;
					this.SendPropertyChanged("Capacity");
					this.OnCapacityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_RoomBooking", Storage="_RoomBookings", ThisKey="RoomID", OtherKey="RoomID")]
		public EntitySet<RoomBooking> RoomBookings
		{
			get
			{
				return this._RoomBookings;
			}
			set
			{
				this._RoomBookings.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_Cleaning", Storage="_Cleanings", ThisKey="RoomID", OtherKey="RoomID")]
		public EntitySet<Cleaning> Cleanings
		{
			get
			{
				return this._Cleanings;
			}
			set
			{
				this._Cleanings.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_RoomBookings(RoomBooking entity)
		{
			this.SendPropertyChanging();
			entity.Room = this;
		}
		
		private void detach_RoomBookings(RoomBooking entity)
		{
			this.SendPropertyChanging();
			entity.Room = null;
		}
		
		private void attach_Cleanings(Cleaning entity)
		{
			this.SendPropertyChanging();
			entity.Room = this;
		}
		
		private void detach_Cleanings(Cleaning entity)
		{
			this.SendPropertyChanging();
			entity.Room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RoomBooking")]
	public partial class RoomBooking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RoomBookingID;
		
		private int _RoomID;
		
		private string _GuestName;
		
		private string _GuestPhone;
		
		private int _NumberOfAdult;
		
		private System.Nullable<int> _NumberOfChild;
		
		private int _PricePerRoom;
		
		private System.Nullable<int> _PriceOfAdditionalBed;
		
		private System.DateTime _StartDate;
		
		private System.DateTime _EndDate;
		
		private int _BookingStatus;
		
		private string _AdditionalInfo;
		
		private System.Nullable<int> _AlreadyPaid;
		
		private EntityRef<Room> _Room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoomBookingIDChanging(int value);
    partial void OnRoomBookingIDChanged();
    partial void OnRoomIDChanging(int value);
    partial void OnRoomIDChanged();
    partial void OnGuestNameChanging(string value);
    partial void OnGuestNameChanged();
    partial void OnGuestPhoneChanging(string value);
    partial void OnGuestPhoneChanged();
    partial void OnNumberOfAdultChanging(int value);
    partial void OnNumberOfAdultChanged();
    partial void OnNumberOfChildChanging(System.Nullable<int> value);
    partial void OnNumberOfChildChanged();
    partial void OnPricePerRoomChanging(int value);
    partial void OnPricePerRoomChanged();
    partial void OnPriceOfAdditionalBedChanging(System.Nullable<int> value);
    partial void OnPriceOfAdditionalBedChanged();
    partial void OnStartDateChanging(System.DateTime value);
    partial void OnStartDateChanged();
    partial void OnEndDateChanging(System.DateTime value);
    partial void OnEndDateChanged();
    partial void OnBookingStatusChanging(int value);
    partial void OnBookingStatusChanged();
    partial void OnAdditionalInfoChanging(string value);
    partial void OnAdditionalInfoChanged();
    partial void OnAlreadyPaidChanging(System.Nullable<int> value);
    partial void OnAlreadyPaidChanged();
    #endregion
		
		public RoomBooking()
		{
			this._Room = default(EntityRef<Room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomBookingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RoomBookingID
		{
			get
			{
				return this._RoomBookingID;
			}
			set
			{
				if ((this._RoomBookingID != value))
				{
					this.OnRoomBookingIDChanging(value);
					this.SendPropertyChanging();
					this._RoomBookingID = value;
					this.SendPropertyChanged("RoomBookingID");
					this.OnRoomBookingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomID", DbType="Int NOT NULL")]
		public int RoomID
		{
			get
			{
				return this._RoomID;
			}
			set
			{
				if ((this._RoomID != value))
				{
					if (this._Room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoomIDChanging(value);
					this.SendPropertyChanging();
					this._RoomID = value;
					this.SendPropertyChanged("RoomID");
					this.OnRoomIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestName", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GuestName
		{
			get
			{
				return this._GuestName;
			}
			set
			{
				if ((this._GuestName != value))
				{
					this.OnGuestNameChanging(value);
					this.SendPropertyChanging();
					this._GuestName = value;
					this.SendPropertyChanged("GuestName");
					this.OnGuestNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestPhone", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string GuestPhone
		{
			get
			{
				return this._GuestPhone;
			}
			set
			{
				if ((this._GuestPhone != value))
				{
					this.OnGuestPhoneChanging(value);
					this.SendPropertyChanging();
					this._GuestPhone = value;
					this.SendPropertyChanged("GuestPhone");
					this.OnGuestPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfAdult", DbType="Int NOT NULL")]
		public int NumberOfAdult
		{
			get
			{
				return this._NumberOfAdult;
			}
			set
			{
				if ((this._NumberOfAdult != value))
				{
					this.OnNumberOfAdultChanging(value);
					this.SendPropertyChanging();
					this._NumberOfAdult = value;
					this.SendPropertyChanged("NumberOfAdult");
					this.OnNumberOfAdultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberOfChild", DbType="Int")]
		public System.Nullable<int> NumberOfChild
		{
			get
			{
				return this._NumberOfChild;
			}
			set
			{
				if ((this._NumberOfChild != value))
				{
					this.OnNumberOfChildChanging(value);
					this.SendPropertyChanging();
					this._NumberOfChild = value;
					this.SendPropertyChanged("NumberOfChild");
					this.OnNumberOfChildChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PricePerRoom", DbType="Int NOT NULL")]
		public int PricePerRoom
		{
			get
			{
				return this._PricePerRoom;
			}
			set
			{
				if ((this._PricePerRoom != value))
				{
					this.OnPricePerRoomChanging(value);
					this.SendPropertyChanging();
					this._PricePerRoom = value;
					this.SendPropertyChanged("PricePerRoom");
					this.OnPricePerRoomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PriceOfAdditionalBed", DbType="Int")]
		public System.Nullable<int> PriceOfAdditionalBed
		{
			get
			{
				return this._PriceOfAdditionalBed;
			}
			set
			{
				if ((this._PriceOfAdditionalBed != value))
				{
					this.OnPriceOfAdditionalBedChanging(value);
					this.SendPropertyChanging();
					this._PriceOfAdditionalBed = value;
					this.SendPropertyChanged("PriceOfAdditionalBed");
					this.OnPriceOfAdditionalBedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="Date NOT NULL")]
		public System.DateTime StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this.OnStartDateChanging(value);
					this.SendPropertyChanging();
					this._StartDate = value;
					this.SendPropertyChanged("StartDate");
					this.OnStartDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="Date NOT NULL")]
		public System.DateTime EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this.OnEndDateChanging(value);
					this.SendPropertyChanging();
					this._EndDate = value;
					this.SendPropertyChanged("EndDate");
					this.OnEndDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BookingStatus", DbType="Int NOT NULL")]
		public int BookingStatus
		{
			get
			{
				return this._BookingStatus;
			}
			set
			{
				if ((this._BookingStatus != value))
				{
					this.OnBookingStatusChanging(value);
					this.SendPropertyChanging();
					this._BookingStatus = value;
					this.SendPropertyChanged("BookingStatus");
					this.OnBookingStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalInfo", DbType="NVarChar(MAX)")]
		public string AdditionalInfo
		{
			get
			{
				return this._AdditionalInfo;
			}
			set
			{
				if ((this._AdditionalInfo != value))
				{
					this.OnAdditionalInfoChanging(value);
					this.SendPropertyChanging();
					this._AdditionalInfo = value;
					this.SendPropertyChanged("AdditionalInfo");
					this.OnAdditionalInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlreadyPaid", DbType="Int")]
		public System.Nullable<int> AlreadyPaid
		{
			get
			{
				return this._AlreadyPaid;
			}
			set
			{
				if ((this._AlreadyPaid != value))
				{
					this.OnAlreadyPaidChanging(value);
					this.SendPropertyChanging();
					this._AlreadyPaid = value;
					this.SendPropertyChanged("AlreadyPaid");
					this.OnAlreadyPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_RoomBooking", Storage="_Room", ThisKey="RoomID", OtherKey="RoomID", IsForeignKey=true)]
		public Room Room
		{
			get
			{
				return this._Room.Entity;
			}
			set
			{
				Room previousValue = this._Room.Entity;
				if (((previousValue != value) 
							|| (this._Room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room.Entity = null;
						previousValue.RoomBookings.Remove(this);
					}
					this._Room.Entity = value;
					if ((value != null))
					{
						value.RoomBookings.Add(this);
						this._RoomID = value.RoomID;
					}
					else
					{
						this._RoomID = default(int);
					}
					this.SendPropertyChanged("Room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExpensesItems")]
	public partial class ExpensesItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExpensesItemID;
		
		private System.Nullable<int> _ParentExpensesItemID;
		
		private string _Name;
		
		private EntitySet<ExpensesItem> _ExpensesItems;
		
		private EntitySet<ExpensesDetail> _ExpensesDetails;
		
		private EntityRef<ExpensesItem> _ExpensesItem1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExpensesItemIDChanging(int value);
    partial void OnExpensesItemIDChanged();
    partial void OnParentExpensesItemIDChanging(System.Nullable<int> value);
    partial void OnParentExpensesItemIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public ExpensesItem()
		{
			this._ExpensesItems = new EntitySet<ExpensesItem>(new Action<ExpensesItem>(this.attach_ExpensesItems), new Action<ExpensesItem>(this.detach_ExpensesItems));
			this._ExpensesDetails = new EntitySet<ExpensesDetail>(new Action<ExpensesDetail>(this.attach_ExpensesDetails), new Action<ExpensesDetail>(this.detach_ExpensesDetails));
			this._ExpensesItem1 = default(EntityRef<ExpensesItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpensesItemID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExpensesItemID
		{
			get
			{
				return this._ExpensesItemID;
			}
			set
			{
				if ((this._ExpensesItemID != value))
				{
					this.OnExpensesItemIDChanging(value);
					this.SendPropertyChanging();
					this._ExpensesItemID = value;
					this.SendPropertyChanged("ExpensesItemID");
					this.OnExpensesItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentExpensesItemID", DbType="Int")]
		public System.Nullable<int> ParentExpensesItemID
		{
			get
			{
				return this._ParentExpensesItemID;
			}
			set
			{
				if ((this._ParentExpensesItemID != value))
				{
					if (this._ExpensesItem1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnParentExpensesItemIDChanging(value);
					this.SendPropertyChanging();
					this._ParentExpensesItemID = value;
					this.SendPropertyChanged("ParentExpensesItemID");
					this.OnParentExpensesItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExpensesItem_ExpensesItem", Storage="_ExpensesItems", ThisKey="ExpensesItemID", OtherKey="ParentExpensesItemID")]
		public EntitySet<ExpensesItem> ExpensesItems
		{
			get
			{
				return this._ExpensesItems;
			}
			set
			{
				this._ExpensesItems.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExpensesItem_ExpensesDetail", Storage="_ExpensesDetails", ThisKey="ExpensesItemID", OtherKey="ExpensesItemID")]
		public EntitySet<ExpensesDetail> ExpensesDetails
		{
			get
			{
				return this._ExpensesDetails;
			}
			set
			{
				this._ExpensesDetails.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExpensesItem_ExpensesItem", Storage="_ExpensesItem1", ThisKey="ParentExpensesItemID", OtherKey="ExpensesItemID", IsForeignKey=true)]
		public ExpensesItem ExpensesItem1
		{
			get
			{
				return this._ExpensesItem1.Entity;
			}
			set
			{
				ExpensesItem previousValue = this._ExpensesItem1.Entity;
				if (((previousValue != value) 
							|| (this._ExpensesItem1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExpensesItem1.Entity = null;
						previousValue.ExpensesItems.Remove(this);
					}
					this._ExpensesItem1.Entity = value;
					if ((value != null))
					{
						value.ExpensesItems.Add(this);
						this._ParentExpensesItemID = value.ExpensesItemID;
					}
					else
					{
						this._ParentExpensesItemID = default(Nullable<int>);
					}
					this.SendPropertyChanged("ExpensesItem1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ExpensesItems(ExpensesItem entity)
		{
			this.SendPropertyChanging();
			entity.ExpensesItem1 = this;
		}
		
		private void detach_ExpensesItems(ExpensesItem entity)
		{
			this.SendPropertyChanging();
			entity.ExpensesItem1 = null;
		}
		
		private void attach_ExpensesDetails(ExpensesDetail entity)
		{
			this.SendPropertyChanging();
			entity.ExpensesItem = this;
		}
		
		private void detach_ExpensesDetails(ExpensesDetail entity)
		{
			this.SendPropertyChanging();
			entity.ExpensesItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExpensesDetails")]
	public partial class ExpensesDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ExpensesDetailsID;
		
		private int _ExpensesItemID;
		
		private System.DateTime _Date;
		
		private double _Cost;
		
		private string _Description;
		
		private EntityRef<ExpensesItem> _ExpensesItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnExpensesDetailsIDChanging(int value);
    partial void OnExpensesDetailsIDChanged();
    partial void OnExpensesItemIDChanging(int value);
    partial void OnExpensesItemIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnCostChanging(double value);
    partial void OnCostChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public ExpensesDetail()
		{
			this._ExpensesItem = default(EntityRef<ExpensesItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpensesDetailsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ExpensesDetailsID
		{
			get
			{
				return this._ExpensesDetailsID;
			}
			set
			{
				if ((this._ExpensesDetailsID != value))
				{
					this.OnExpensesDetailsIDChanging(value);
					this.SendPropertyChanging();
					this._ExpensesDetailsID = value;
					this.SendPropertyChanged("ExpensesDetailsID");
					this.OnExpensesDetailsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpensesItemID", DbType="Int NOT NULL")]
		public int ExpensesItemID
		{
			get
			{
				return this._ExpensesItemID;
			}
			set
			{
				if ((this._ExpensesItemID != value))
				{
					if (this._ExpensesItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnExpensesItemIDChanging(value);
					this.SendPropertyChanging();
					this._ExpensesItemID = value;
					this.SendPropertyChanged("ExpensesItemID");
					this.OnExpensesItemIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Float NOT NULL")]
		public double Cost
		{
			get
			{
				return this._Cost;
			}
			set
			{
				if ((this._Cost != value))
				{
					this.OnCostChanging(value);
					this.SendPropertyChanging();
					this._Cost = value;
					this.SendPropertyChanged("Cost");
					this.OnCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ExpensesItem_ExpensesDetail", Storage="_ExpensesItem", ThisKey="ExpensesItemID", OtherKey="ExpensesItemID", IsForeignKey=true)]
		public ExpensesItem ExpensesItem
		{
			get
			{
				return this._ExpensesItem.Entity;
			}
			set
			{
				ExpensesItem previousValue = this._ExpensesItem.Entity;
				if (((previousValue != value) 
							|| (this._ExpensesItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ExpensesItem.Entity = null;
						previousValue.ExpensesDetails.Remove(this);
					}
					this._ExpensesItem.Entity = value;
					if ((value != null))
					{
						value.ExpensesDetails.Add(this);
						this._ExpensesItemID = value.ExpensesItemID;
					}
					else
					{
						this._ExpensesItemID = default(int);
					}
					this.SendPropertyChanged("ExpensesItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cleaning")]
	public partial class Cleaning : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CleaningID;
		
		private int _RoomID;
		
		private System.DateTime _DateOfCleaning;
		
		private EntityRef<Room> _Room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCleaningIDChanging(int value);
    partial void OnCleaningIDChanged();
    partial void OnRoomIDChanging(int value);
    partial void OnRoomIDChanged();
    partial void OnDateOfCleaningChanging(System.DateTime value);
    partial void OnDateOfCleaningChanged();
    #endregion
		
		public Cleaning()
		{
			this._Room = default(EntityRef<Room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CleaningID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CleaningID
		{
			get
			{
				return this._CleaningID;
			}
			set
			{
				if ((this._CleaningID != value))
				{
					this.OnCleaningIDChanging(value);
					this.SendPropertyChanging();
					this._CleaningID = value;
					this.SendPropertyChanged("CleaningID");
					this.OnCleaningIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomID", DbType="Int NOT NULL")]
		public int RoomID
		{
			get
			{
				return this._RoomID;
			}
			set
			{
				if ((this._RoomID != value))
				{
					if (this._Room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoomIDChanging(value);
					this.SendPropertyChanging();
					this._RoomID = value;
					this.SendPropertyChanged("RoomID");
					this.OnRoomIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfCleaning", DbType="Date NOT NULL")]
		public System.DateTime DateOfCleaning
		{
			get
			{
				return this._DateOfCleaning;
			}
			set
			{
				if ((this._DateOfCleaning != value))
				{
					this.OnDateOfCleaningChanging(value);
					this.SendPropertyChanging();
					this._DateOfCleaning = value;
					this.SendPropertyChanged("DateOfCleaning");
					this.OnDateOfCleaningChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_Cleaning", Storage="_Room", ThisKey="RoomID", OtherKey="RoomID", IsForeignKey=true)]
		public Room Room
		{
			get
			{
				return this._Room.Entity;
			}
			set
			{
				Room previousValue = this._Room.Entity;
				if (((previousValue != value) 
							|| (this._Room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room.Entity = null;
						previousValue.Cleanings.Remove(this);
					}
					this._Room.Entity = value;
					if ((value != null))
					{
						value.Cleanings.Add(this);
						this._RoomID = value.RoomID;
					}
					else
					{
						this._RoomID = default(int);
					}
					this.SendPropertyChanged("Room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UtilitiesItems")]
	public partial class UtilitiesItem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UtilitiesItemsID;
		
		private string _Name;
		
		private EntitySet<UtilitiesItemsDetail> _UtilitiesItemsDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUtilitiesItemsIDChanging(int value);
    partial void OnUtilitiesItemsIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
		
		public UtilitiesItem()
		{
			this._UtilitiesItemsDetails = new EntitySet<UtilitiesItemsDetail>(new Action<UtilitiesItemsDetail>(this.attach_UtilitiesItemsDetails), new Action<UtilitiesItemsDetail>(this.detach_UtilitiesItemsDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilitiesItemsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UtilitiesItemsID
		{
			get
			{
				return this._UtilitiesItemsID;
			}
			set
			{
				if ((this._UtilitiesItemsID != value))
				{
					this.OnUtilitiesItemsIDChanging(value);
					this.SendPropertyChanging();
					this._UtilitiesItemsID = value;
					this.SendPropertyChanged("UtilitiesItemsID");
					this.OnUtilitiesItemsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UtilitiesItem_UtilitiesItemsDetail", Storage="_UtilitiesItemsDetails", ThisKey="UtilitiesItemsID", OtherKey="UtilitiesItemsID")]
		public EntitySet<UtilitiesItemsDetail> UtilitiesItemsDetails
		{
			get
			{
				return this._UtilitiesItemsDetails;
			}
			set
			{
				this._UtilitiesItemsDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UtilitiesItemsDetails(UtilitiesItemsDetail entity)
		{
			this.SendPropertyChanging();
			entity.UtilitiesItem = this;
		}
		
		private void detach_UtilitiesItemsDetails(UtilitiesItemsDetail entity)
		{
			this.SendPropertyChanging();
			entity.UtilitiesItem = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UtilitiesItemsDetails")]
	public partial class UtilitiesItemsDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UtilitiesItemsDetailsID;
		
		private int _UtilitiesItemsID;
		
		private System.DateTime _Date;
		
		private double _Value;
		
		private string _Description;
		
		private EntityRef<UtilitiesItem> _UtilitiesItem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUtilitiesItemsDetailsIDChanging(int value);
    partial void OnUtilitiesItemsDetailsIDChanged();
    partial void OnUtilitiesItemsIDChanging(int value);
    partial void OnUtilitiesItemsIDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnValueChanging(double value);
    partial void OnValueChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public UtilitiesItemsDetail()
		{
			this._UtilitiesItem = default(EntityRef<UtilitiesItem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilitiesItemsDetailsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UtilitiesItemsDetailsID
		{
			get
			{
				return this._UtilitiesItemsDetailsID;
			}
			set
			{
				if ((this._UtilitiesItemsDetailsID != value))
				{
					this.OnUtilitiesItemsDetailsIDChanging(value);
					this.SendPropertyChanging();
					this._UtilitiesItemsDetailsID = value;
					this.SendPropertyChanged("UtilitiesItemsDetailsID");
					this.OnUtilitiesItemsDetailsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilitiesItemsID", DbType="Int NOT NULL")]
		public int UtilitiesItemsID
		{
			get
			{
				return this._UtilitiesItemsID;
			}
			set
			{
				if ((this._UtilitiesItemsID != value))
				{
					if (this._UtilitiesItem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUtilitiesItemsIDChanging(value);
					this.SendPropertyChanging();
					this._UtilitiesItemsID = value;
					this.SendPropertyChanged("UtilitiesItemsID");
					this.OnUtilitiesItemsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Float NOT NULL")]
		public double Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="UtilitiesItem_UtilitiesItemsDetail", Storage="_UtilitiesItem", ThisKey="UtilitiesItemsID", OtherKey="UtilitiesItemsID", IsForeignKey=true)]
		public UtilitiesItem UtilitiesItem
		{
			get
			{
				return this._UtilitiesItem.Entity;
			}
			set
			{
				UtilitiesItem previousValue = this._UtilitiesItem.Entity;
				if (((previousValue != value) 
							|| (this._UtilitiesItem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._UtilitiesItem.Entity = null;
						previousValue.UtilitiesItemsDetails.Remove(this);
					}
					this._UtilitiesItem.Entity = value;
					if ((value != null))
					{
						value.UtilitiesItemsDetails.Add(this);
						this._UtilitiesItemsID = value.UtilitiesItemsID;
					}
					else
					{
						this._UtilitiesItemsID = default(int);
					}
					this.SendPropertyChanged("UtilitiesItem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomData")]
	public partial class CustomData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CustomDataID;
		
		private string _JSONData;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomDataIDChanging(int value);
    partial void OnCustomDataIDChanged();
    partial void OnJSONDataChanging(string value);
    partial void OnJSONDataChanged();
    #endregion
		
		public CustomData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomDataID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CustomDataID
		{
			get
			{
				return this._CustomDataID;
			}
			set
			{
				if ((this._CustomDataID != value))
				{
					this.OnCustomDataIDChanging(value);
					this.SendPropertyChanging();
					this._CustomDataID = value;
					this.SendPropertyChanged("CustomDataID");
					this.OnCustomDataIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JSONData", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string JSONData
		{
			get
			{
				return this._JSONData;
			}
			set
			{
				if ((this._JSONData != value))
				{
					this.OnJSONDataChanging(value);
					this.SendPropertyChanging();
					this._JSONData = value;
					this.SendPropertyChanged("JSONData");
					this.OnJSONDataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
