<?xml version="1.0" encoding="utf-8"?><Database Name="MyHotelDB" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=user-pc\sqlexpress;Initial Catalog=MyHotelDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MyHotelDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="RoomID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_RoomBooking" Member="RoomBookings" ThisKey="RoomID" OtherKey="RoomID" Type="RoomBooking" />
    </Type>
  </Table>
  <Table Name="dbo.RoomBooking" Member="RoomBookings">
    <Type Name="RoomBooking">
      <Column Name="RoomBookingID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GuestName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="GuestPhone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfAdult" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfChild" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PricePerRoom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PriceOfAdditionalBed" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BookingStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdditionalInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Room_RoomBooking" Member="Room" ThisKey="RoomID" OtherKey="RoomID" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
</Database>